# Generated by Django 5.2.9 on 2025-12-16 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poster_url', models.URLField(max_length=500)),
                ('backdrop_url', models.URLField(blank=True, max_length=500, null=True)),
                ('release_year', models.IntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('trailer_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cast', models.TextField(blank=True, help_text='Comma-separated list of actors')),
                ('director', models.CharField(blank=True, max_length=255)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_top_rated', models.BooleanField(default=False)),
                ('is_new_release', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='movies.movie')),
            ],
            options={
                'unique_together': {('user_id', 'movie')},
            },
        ),
    ]
