# Generated by Django 5.2.9 on 2025-12-16 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_notification_userlist_userpreferences_userprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='movies.reviewcomment')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.userreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('media_type', models.CharField(max_length=10)),
                ('avg_sentiment_score', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('tmdb_id', 'media_type')},
            },
        ),
        migrations.CreateModel(
            name='UserActivityStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_lists', models.IntegerField(default=0)),
                ('total_followers', models.IntegerField(default=0)),
                ('total_following', models.IntegerField(default=0)),
                ('total_awards_given', models.IntegerField(default=0)),
                ('total_awards_received', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('user_level', models.IntegerField(default=1)),
                ('experience_points', models.IntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_tmdb_id', models.IntegerField()),
                ('for_media_type', models.CharField(max_length=10)),
                ('recommended_tmdb_id', models.IntegerField()),
                ('recommended_media_type', models.CharField(max_length=10)),
                ('recommended_title', models.CharField(max_length=255)),
                ('recommended_poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='movies.userlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'list')},
            },
        ),
        migrations.CreateModel(
            name='ReviewAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('outstanding', 'Outstanding'), ('perfect', 'Perfect'), ('great', 'Great'), ('helpful', 'Helpful'), ('insightful', 'Insightful'), ('funny', 'Funny')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='movies.userreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'review', 'award_type')},
            },
        ),
        migrations.CreateModel(
            name='ReviewInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('report', 'Report')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='movies.userreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'review', 'interaction_type')},
            },
        ),
        migrations.CreateModel(
            name='UserCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=255)),
                ('match_percentage', models.IntegerField(default=0)),
                ('member_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'community_name')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_votes', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='movies.userrecommendation')),
            ],
            options={
                'unique_together': {('user', 'recommendation')},
            },
        ),
    ]
