# Generated by Django 5.2.9 on 2025-12-17 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_notificationsettings_recommendationcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BanditExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_type', models.CharField(choices=[('epsilon_greedy', 'Epsilon Greedy'), ('thompson_sampling', 'Thompson Sampling'), ('ucb', 'Upper Confidence Bound')], max_length=30)),
                ('arm_chosen', models.CharField(max_length=100)),
                ('reward', models.FloatField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('exploration_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandit_experiments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('media_type', models.CharField(max_length=10)),
                ('embedding', models.JSONField()),
                ('embedding_version', models.CharField(default='v1', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('tmdb_id', 'media_type')},
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('media_type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('recommendation_type', models.CharField(choices=[('collaborative', 'Collaborative Filtering'), ('content', 'Content-Based'), ('ai', 'AI-Generated'), ('hybrid', 'Hybrid')], max_length=20)),
                ('reason', models.TextField()),
                ('confidence', models.FloatField()),
                ('relevance_score', models.FloatField()),
                ('user_interacted', models.BooleanField(default=False)),
                ('user_feedback', models.CharField(blank=True, choices=[('liked', 'Liked'), ('disliked', 'Disliked'), ('not_interested', 'Not Interested')], max_length=20, null=True)),
                ('ai_explanation', models.TextField(blank=True, null=True)),
                ('source_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
                ('contribution_score', models.FloatField()),
                ('feature_value', models.FloatField(blank=True, null=True)),
                ('was_successful', models.BooleanField(blank=True, null=True)),
                ('outcome_type', models.CharField(blank=True, choices=[('clicked', 'Clicked'), ('watchlisted', 'Added to Watchlist'), ('rated_high', 'Rated High'), ('ignored', 'Ignored'), ('dismissed', 'Dismissed')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_contributions', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_contributions', to='movies.recommendation')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('view_duration', models.IntegerField(blank=True, null=True)),
                ('added_to_watchlist', models.BooleanField(default=False)),
                ('added_to_watchlist_at', models.DateTimeField(blank=True, null=True)),
                ('actually_watched', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('effectiveness_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='movies.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_metrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SemanticEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('media_type', models.CharField(max_length=10)),
                ('embedding', models.JSONField()),
                ('text_source', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('tmdb_id', 'media_type')},
            },
        ),
        migrations.CreateModel(
            name='TmdbMovieCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('media_type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('overview', models.TextField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.CharField(blank=True, max_length=20, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('genre_ids', models.JSONField(blank=True, null=True)),
                ('original_language', models.CharField(blank=True, max_length=10, null=True)),
                ('adult', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tmdb_id'], name='movies_tmdb_tmdb_id_244956_idx'), models.Index(fields=['media_type'], name='movies_tmdb_media_t_83784e_idx'), models.Index(fields=['popularity'], name='movies_tmdb_popular_296738_idx')],
                'unique_together': {('tmdb_id', 'media_type')},
            },
        ),
        migrations.CreateModel(
            name='TmdbTrainingData',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('original_title', models.CharField(blank=True, max_length=500, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.CharField(blank=True, max_length=20, null=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('runtime', models.FloatField(blank=True, null=True)),
                ('budget', models.FloatField(blank=True, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('original_language', models.CharField(blank=True, max_length=10, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('production_companies', models.TextField(blank=True, null=True)),
                ('production_countries', models.TextField(blank=True, null=True)),
                ('spoken_languages', models.TextField(blank=True, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('director_of_photography', models.CharField(blank=True, max_length=255, null=True)),
                ('writers', models.TextField(blank=True, null=True)),
                ('producers', models.TextField(blank=True, null=True)),
                ('music_composer', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('imdb_votes', models.FloatField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['genres'], name='movies_tmdb_genres_8ef71d_idx'), models.Index(fields=['popularity'], name='movies_tmdb_popular_135c33_idx'), models.Index(fields=['release_date'], name='movies_tmdb_release_15f2f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('embedding_version', models.CharField(default='v1', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=0.5)),
                ('success_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0)),
                ('learning_rate', models.FloatField(default=0.1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_weights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'feature_name')},
            },
        ),
        migrations.CreateModel(
            name='UserSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('common_movies', models.IntegerField()),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
