# Generated by Django 6.0 on 2026-01-17 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_ml_features_migration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('tmdb_id', models.IntegerField()),
                ('media_type', models.CharField(default='movie', max_length=10)),
                ('action', models.CharField(choices=[('click', 'Click'), ('watch', 'Watch')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['query'], name='movies_sear_query_15292c_idx'), models.Index(fields=['tmdb_id'], name='movies_sear_tmdb_id_313718_idx')],
            },
        ),
    ]
