# Generated by Django 5.2.12 on 2026-04-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_tmdbmoviecache_genre_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'New Follower'), ('like', 'Review Liked'), ('comment', 'New Comment'), ('list_follow', 'List Followed'), ('recommendation', 'New Recommendation')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sentimentanalytics',
            name='media_type',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='sentimentanalytics',
            name='tmdb_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='media_type',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='tmdb_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='media_type',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='tmdb_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userwatchlist',
            name='media_type',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userwatchlist',
            name='tmdb_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='viewinghistory',
            name='media_type',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='viewinghistory',
            name='tmdb_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='viewinghistory',
            name='watched_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
