# Generated by Django 5.2.12 on 2026-04-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_media_type',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_tmdb_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
