# Generated by Django 5.2.12 on 2026-04-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_notification_related_media_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSentimentCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('classification', models.CharField(max_length=10)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_cache', to='movies.userreview')),
            ],
        ),
    ]
