# Generated by Django 5.2.12 on 2026-04-03 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_userrating_user_fk'),
        ('movies', '0010_reviewsentimentcache'),
    ]

    operations = [
    ]
