# Generated by Django 5.2.12 on 2026-04-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_merge_20260403_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
