# Generated by Django 6.0.3 on 2026-05-03 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_change_profile_image_url_to_textfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userfavorites',
            index=models.Index(fields=['user', '-added_at'], name='favorites_user_added_idx'),
        ),
        migrations.AddIndex(
            model_name='userreview',
            index=models.Index(fields=['user', '-created_at'], name='review_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userwatchlist',
            index=models.Index(fields=['user', '-added_at'], name='watchlist_user_added_idx'),
        ),
        migrations.AddIndex(
            model_name='viewinghistory',
            index=models.Index(fields=['user', '-watched_at'], name='history_user_watched_idx'),
        ),
    ]
